### PR TITLE
New Event for Response Stream

### PR DESCRIPTION
**Pull request by adamtheadmin**
Emit Streams for response data, instead of one handler for all response data

### CODE REVIEW

**Review by brozeph — COMMENTED** [review]
Is the general idea to have a raw stream of the response in order to pipe data to it?

**Comment by adamtheadmin** [comment]
The purpose for this branch allows me to add a listener for new responses, and return a separate stream for incoming data. Works best for http data.

**Comment by brozeph** [comment]
If your goal is to create a fork of the response stream while listening for new connections, would the following work for you (this would require no modifications to the `simple-socks` module itself)?

``` javascript
const 
  socks5 = require('simple-socks'),
  stream = require('stream');

let server = socks5.createServer().listen(1080);

server.on('proxyConnect', (info, originalStream) => {
  let forkedStream = originalStream.pipe(new stream.PassThrough());

  forkedStream.on('data', (data) => {
    // do teh stuff with teh data...
  });
});
```

**Comment by brozeph** [comment]
Closing due to inactivity - @lilglower, please hit me with any further questions! I don't know the use case at depth, but I have a strong hunch that what you are trying to accomplish can be handled without modifying the server.

**Pull request closed without merging**
