### PR TITLE
Added bind on interface

### PR DESCRIPTION
**Pull request by intech**

### CODE REVIEW

**Comment by intech** [comment]
ffi module on travis not compiling :angry:

**Comment by killerangel13** [comment]
@intech 

I love you.

**Comment by brozeph** [comment]
@intech - I'm digging this... however, are there additional considerations for Windows or Unix?

**Comment by intech** [comment]
@brozeph sorry, only unix. Tested on debian, well works.

**Comment by brozeph** [comment]
Closing this given time since proposal... I was reluctant to merge due to the FFI dependency.

**Pull request closed without merging**
